### ISSUE TITLE
Enlace a version 11 de la traduccion requiere version 12 para instalarse

### ISSUE THREAD

**Issue by markhlam** [lozanoje/foundryvtt-es#7]
Hola!

Me he instalado la version 11 de Foundry para mantener compatibilidad con el sistema TOR2e, pero al intentar instalar la traduccion del Core para version 11 resulta que el manifest está cambiado y me exige version 12 aunque en el enlace pone que es el válido para version 11

**Comment by lozanoje** [comment]
Intenta ahora, lo he puesto compatible con v11, aunque yo me descargaría esta versión, que es la última v11.315:

https://github.com/lozanoje/foundryvtt-es/tree/31d0c4033a9fd609b185a75b2c208f2636623a81
